/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl;

import beans.UserBean;
import java.awt.Container;
import java.awt.Toolkit;
import services.UserReportsServices;

/**
 *
 * @author hp
 */
public class MainFrame extends javax.swing.JFrame {

    public static Container c;   //c is reference type member variable
    private int activityid;
    private int userid;

   

    public MainFrame(int activityid, UserBean objbean) {
       
        setUndecorated(true);    //it removes taskbar
        initComponents();
        setSize(Toolkit.getDefaultToolkit().getScreenSize());    //full screen
        c = this.getContentPane();  //creates container object
         this.activityid = activityid;
         this.userid=objbean.getUserid();
        if(objbean.getUsertype().equalsIgnoreCase("user"))
        {
            mbMainFrame.remove(mnuReports); //removes reports from main frame menu
            mnuMaintenance.remove(miManageUsers);   //removes manage users from maintenance in main frame
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mbMainFrame = new javax.swing.JMenuBar();
        mnuLogout = new javax.swing.JMenu();
        mnuMaintenance = new javax.swing.JMenu();
        miManageUsers = new javax.swing.JMenuItem();
        miMangaeProfile = new javax.swing.JMenuItem();
        mnuReports = new javax.swing.JMenu();
        miUserReports = new javax.swing.JMenuItem();
        miActivityReports = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mbMainFrame.setBackground(new java.awt.Color(102, 102, 255));

        mnuLogout.setText("Logout");
        mnuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuLogoutMouseClicked(evt);
            }
        });
        mbMainFrame.add(mnuLogout);

        mnuMaintenance.setText("Maintenance");

        miManageUsers.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        miManageUsers.setText("Manage Users");
        miManageUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miManageUsersActionPerformed(evt);
            }
        });
        mnuMaintenance.add(miManageUsers);

        miMangaeProfile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        miMangaeProfile.setText("Manage Profile");
        miMangaeProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miMangaeProfileActionPerformed(evt);
            }
        });
        mnuMaintenance.add(miMangaeProfile);

        mbMainFrame.add(mnuMaintenance);

        mnuReports.setText("Reports");

        miUserReports.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        miUserReports.setText("User Reports");
        miUserReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUserReportsActionPerformed(evt);
            }
        });
        mnuReports.add(miUserReports);

        miActivityReports.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        miActivityReports.setText("User Activity Reports");
        miActivityReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miActivityReportsActionPerformed(evt);
            }
        });
        mnuReports.add(miActivityReports);

        mbMainFrame.add(mnuReports);

        setJMenuBar(mbMainFrame);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuLogoutMouseClicked
        // logout:events:mouse:mouse Clicked (single action)
        
        SignInPage si = new SignInPage();
        si.setVisible(true);

        if (UserReportsServices.updateLogoutTime(activityid)) {
            this.dispose();
        } else {
            System.out.println("Record not added");
        }
    }//GEN-LAST:event_mnuLogoutMouseClicked

    private void miManageUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miManageUsersActionPerformed
        // manage user:events:action performed (single action)
        c.removeAll();    //remove all the tabs opened currently
        c.setVisible(false);  //mainframe nhi dhikhega
        ManageUsers objmu = new ManageUsers(); //manage users panel hai jo mainframe pr dependent hai
        objmu.setBounds(10, 10, 1350, 720);   //10,10 are the x,y coordinates and 1350,720 are the width and height
        c.add(objmu);    //add data of manage users to container
        c.setVisible(true);//shows manage users panel
    }//GEN-LAST:event_miManageUsersActionPerformed

    private void miUserReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUserReportsActionPerformed
        c.removeAll();    //remove all the panels opened currently
        c.setVisible(false);
        UserReports objur = new UserReports();
        objur.setBounds(10, 10, 1350, 720);   //10,10 are the x,y coordinates and 720,1350 are the height and width
        c.add(objur);    //add data of manage users to container
        c.setVisible(true);
    }//GEN-LAST:event_miUserReportsActionPerformed

    private void miMangaeProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMangaeProfileActionPerformed

        c.removeAll();    //remove all the panels opened currently
        c.setVisible(false);
        ManageProfile mp = new ManageProfile(userid);
        mp.setBounds(10, 10, 1350, 720);   //10,10 are the x,y coordinates and 700,600 are the heights and width
        c.add(mp);    //add data of manage users to container
        c.setVisible(true);
    }//GEN-LAST:event_miMangaeProfileActionPerformed

    private void miActivityReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miActivityReportsActionPerformed
        c.removeAll();    //remove all the panels opened currently
        c.setVisible(false);
        UserActivityReports uar = new UserActivityReports();
        uar.setBounds(10, 10, 1350, 720);   //10,10 are the x,y coordinates and 720,1350 are the height and width
        c.add(uar);    //add data of manage users to container
        c.setVisible(true);
    }//GEN-LAST:event_miActivityReportsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //  new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar mbMainFrame;
    private javax.swing.JMenuItem miActivityReports;
    private javax.swing.JMenuItem miManageUsers;
    private javax.swing.JMenuItem miMangaeProfile;
    private javax.swing.JMenuItem miUserReports;
    private javax.swing.JMenu mnuLogout;
    private javax.swing.JMenu mnuMaintenance;
    private javax.swing.JMenu mnuReports;
    // End of variables declaration//GEN-END:variables
}
